"""Added middle man table for role and permissions

Revision ID: 22c9cd2f92fa
Revises: 3ae65a48812c
Create Date: 2026-01-21 23:13:16.084702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c9cd2f92fa'
down_revision = '3ae65a48812c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_user',
    sa.Column('avatar_name', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('mail', sa.VARCHAR(), nullable=True),
    sa.Column('pw_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_id')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
