"""Added remove logs

Revision ID: 31727cd75ac0
Revises: b322ca6fb802
Create Date: 2026-01-25 18:47:56.048522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31727cd75ac0'
down_revision = 'b322ca6fb802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_log',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=15), nullable=False),
    sa.Column('by_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['by_id'], ['user.id'], name='fk_removed_log_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('removed', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('removed')

    op.drop_table('removed_log')
    # ### end Alembic commands ###
