"""Changed user model

Revision ID: 38a6e7764bc7
Revises: 
Create Date: 2026-01-17 20:08:51.169227

"""
from alembic import op
import secrets
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a6e7764bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_association', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.create_unique_constraint('user_target_type_uc', ['target_id', 'target_type', 'user_id'])

    with op.batch_alter_table('tag_association', schema=None) as batch_op:
        batch_op.alter_column('post_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('tag_id', existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table('thumbnail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False, server_default='1970-01-01 00:00:00'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password', new_column_name='pw_hash')
        batch_op.add_column(sa.Column('_key', sa.String(length=64), nullable=True))

    connection = op.get_bind()
    
    user_helper = sa.Table(
        'user',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('_key', sa.String(length=64))
    )

    rows = connection.execute(sa.select(user_helper.c.id)).fetchall()

    for row in rows:
        token = secrets.token_urlsafe(32)
        connection.execute(
            user_helper.update().
            where(user_helper.c.id == row.id).
            values(_key=token)
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_key', nullable=False)
        batch_op.create_index(batch_op.f('ix_user__key'), ['_key'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user__key'))
        batch_op.drop_column('_key')
        batch_op.drop_column('pw_hash')

    with op.batch_alter_table('thumbnail', schema=None) as batch_op:
        batch_op.drop_column('created')

    with op.batch_alter_table('tag_association', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('score_association', schema=None) as batch_op:
        batch_op.drop_constraint('user_target_type_uc', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
