"""Initial migration

Revision ID: 3f26ba1f814c
Revises: e6e037d66f66
Create Date: 2026-01-16 15:37:46.064292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f26ba1f814c'
down_revision = 'e6e037d66f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.alter_column('post_id', new_column_name='target_id', existing_type=sa.Integer())
        batch_op.add_column(sa.Column('target_type', sa.String(length=10), nullable=False, server_default='post'))

    op.execute("UPDATE score_association SET id = (SELECT COUNT(*) FROM score_association s2 WHERE s2.rowid <= score_association.rowid)")

    with op.batch_alter_table('score_association', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.Integer(), nullable=False, primary_key=True)
        batch_op.create_unique_constraint('user_target_type_uc', ['target_id', 'target_type', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_association', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('score_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_constraint('user_target_type_uc', type_='unique')
        batch_op.drop_column('target_type')
        batch_op.drop_column('target_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
