"""Added many-to-many relationship to snapshots

Revision ID: 5935de5d053f
Revises: ad432f7bbbb6
Create Date: 2026-02-24 00:20:41.181913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5935de5d053f'
down_revision = 'ad432f7bbbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_snapshot_association',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'tag_id'),
    sa.UniqueConstraint('snapshot_id', 'tag_id', name='uq_snapshot_tag')
    )

    bind = op.get_bind()
    
    results = bind.execute(sa.text("SELECT id, tags FROM snapshot WHERE tags IS NOT NULL")).fetchall()
    
    for snapshot_id, tags_string in results:
        if tags_string and tags_string.strip():
            tag_names = tags_string.strip().split()
            
            for name in tag_names:
                name = name.lower().strip()
                
                bind.execute(
                    sa.text("INSERT OR IGNORE INTO tag (name) VALUES (:name)"),
                    {"name": name}
                )
                
                tag_id = bind.execute(
                    sa.text("SELECT id FROM tag WHERE name = :name"),
                    {"name": name}
                ).scalar()
                
                bind.execute(
                    sa.text("INSERT OR IGNORE INTO tag_snapshot_association (snapshot_id, tag_id) VALUES (:s_id, :t_id)"),
                    {"s_id": snapshot_id, "t_id": tag_id}
                )

    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.TEXT(), nullable=False))

    op.drop_table('tag_snapshot_association')
    # ### end Alembic commands ###
