"""Changed tag association syntax

Revision ID: 780135ddaef1
Revises: e0fb8fc62025
Create Date: 2026-01-14 22:34:06.020876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780135ddaef1'
down_revision = 'e0fb8fc62025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_association',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_post_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_association')
    # ### end Alembic commands ###
