"""Added priority to roles

Revision ID: 9921781f700e
Revises: 22c9cd2f92fa
Create Date: 2026-01-22 17:21:01.107002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9921781f700e'
down_revision = '22c9cd2f92fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    op.execute("UPDATE role SET priority = 10 WHERE name = 'Admin'")
    op.execute("UPDATE role SET priority = 8 WHERE name = 'Moderator'")
    op.execute("UPDATE role SET priority = 2 WHERE name = 'Janitor'")
    op.execute("UPDATE role SET priority = 1 WHERE name = 'User'")
    
    op.execute("UPDATE role SET priority = id WHERE priority IS NULL")

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('priority', existing_type=sa.Integer(), nullable=False)
        # Remember to give the unique constraint a name!
        batch_op.create_unique_constraint('uq_role_priority', ['priority'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_priority', type_='unique')
        batch_op.drop_column('priority')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
