"""Unique post for tag

Revision ID: b48fb0b58200
Revises: bdeb6bcfb793
Create Date: 2025-10-20 15:29:46.477830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48fb0b58200'
down_revision = 'bdeb6bcfb793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('index_post_id'))
        batch_op.drop_index(batch_op.f('index_tag_id'))
        batch_op.create_unique_constraint('uq_post_tag', ['post_id', 'tag_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_association', schema=None) as batch_op:
        batch_op.drop_constraint('uq_post_tag', type_='unique')
        batch_op.create_index(batch_op.f('index_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('index_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###
