"""Indexed tags

Revision ID: bdeb6bcfb793
Revises: 24c2a2982d3b
Create Date: 2025-10-15 09:21:26.064819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdeb6bcfb793'
down_revision = '24c2a2982d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_association', schema=None) as batch_op:
        batch_op.create_index('index_post_id', ['post_id'], unique=False)
        batch_op.create_index('index_tag_id', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_association', schema=None) as batch_op:
        batch_op.drop_index('index_tag_id')
        batch_op.drop_index('index_post_id')

    # ### end Alembic commands ###
