"""Type & Description columns for tags

Revision ID: d9b94ea570e6
Revises: d0b2829a19a7
Create Date: 2025-11-03 18:38:35.411841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b94ea570e6'
down_revision = 'd0b2829a19a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False, server_default='general'))
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('desc')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
